# Generated by Django 3.1.1 on 2021-01-28 12:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quick_note', '0004_auto_20210128_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 1, 28, 12, 54, 29, 747452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='last_edit',
            field=models.DateField(default=datetime.datetime(2021, 1, 28, 12, 54, 29, 747452, tzinfo=utc), verbose_name='Last Edited date'),
        ),
        migrations.CreateModel(
            name='PublicNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_link', models.URLField(unique=True)),
                ('shared_visits', models.IntegerField(default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_note.usernotes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
